// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package delivery

import (
	json "encoding/json"
	models "github.com/Kudesnjk/DB_TP/internal/models"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCea158a8DecodeGithubComKudesnjkDBTPInternalPostDelivery(in *jlexer.Lexer, out *PostsList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(PostsList, 0, 8)
			} else {
				*out = PostsList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *models.Post
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(models.Post)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCea158a8EncodeGithubComKudesnjkDBTPInternalPostDelivery(out *jwriter.Writer, in PostsList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v PostsList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCea158a8EncodeGithubComKudesnjkDBTPInternalPostDelivery(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostsList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCea158a8EncodeGithubComKudesnjkDBTPInternalPostDelivery(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostsList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCea158a8DecodeGithubComKudesnjkDBTPInternalPostDelivery(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostsList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCea158a8DecodeGithubComKudesnjkDBTPInternalPostDelivery(l, v)
}
func easyjsonCea158a8DecodeGithubComKudesnjkDBTPInternalPostDelivery1(in *jlexer.Lexer, out *PostDelivery) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCea158a8EncodeGithubComKudesnjkDBTPInternalPostDelivery1(out *jwriter.Writer, in PostDelivery) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostDelivery) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCea158a8EncodeGithubComKudesnjkDBTPInternalPostDelivery1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostDelivery) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCea158a8EncodeGithubComKudesnjkDBTPInternalPostDelivery1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostDelivery) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCea158a8DecodeGithubComKudesnjkDBTPInternalPostDelivery1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostDelivery) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCea158a8DecodeGithubComKudesnjkDBTPInternalPostDelivery1(l, v)
}
