// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Forum struct {
	Slug         string `json:"slug"`
	Title        string `json:"title"`
	UserNickname string `json:"user_nickname"`
}

type Post struct {
	ID           int32         `json:"id"`
	Message      string        `json:"message"`
	IsEdited     sql.NullBool  `json:"is_edited"`
	Created      sql.NullTime  `json:"created"`
	ParentID     sql.NullInt32 `json:"parent_id"`
	UserNickname string        `json:"user_nickname"`
	ThreadID     int32         `json:"thread_id"`
}

type Thread struct {
	ID           int32        `json:"id"`
	Title        string       `json:"title"`
	Message      string       `json:"message"`
	Created      sql.NullTime `json:"created"`
	UserNickname string       `json:"user_nickname"`
	ForumID      string       `json:"forum_id"`
}

type User struct {
	Nickname string         `json:"nickname"`
	Email    string         `json:"email"`
	Fullname string         `json:"fullname"`
	About    sql.NullString `json:"about"`
}
